// File generated by FlutterFire CLI & customized for HoneyChain
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Replace the placeholder appId values for Android and iOS with
/// the real ones from the Firebase Console:
///   Console → Project Settings → Your apps → App ID
/// The web appId cannot be reused for Android/iOS — each platform registers
/// a separate app entry in Firebase with a unique appId.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web — used by the verifier React app and Flutter Web builds.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJFOj7F7I7-NIqclH4JLBhDZzvqb9_uIU',
    appId: '1:314717495726:web:d71b1db1dd5c01dbc0a83f',
    messagingSenderId: '314717495726',
    projectId: 'honeychain-40065',
    authDomain: 'honeychain-40065.firebaseapp.com',
    storageBucket: 'honeychain-40065.firebasestorage.app',
    measurementId: 'G-SVJJXDM34B',
  );

  /// Android — register an Android app in Firebase Console and replace
  /// appId with the value from Project Settings → Your apps → Android app.
  /// Also download google-services.json and place it in android/app/.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFOj7F7I7-NIqclH4JLBhDZzvqb9_uIU',
    // TODO: Replace with real Android appId from Firebase Console
    // Format: 1:<project_number>:android:<sha256_hash>
    appId: '1:314717495726:android:d71b1db1dd5c01dbc0a83f',
    messagingSenderId: '314717495726',
    projectId: 'honeychain-40065',
    authDomain: 'honeychain-40065.firebaseapp.com',
    storageBucket: 'honeychain-40065.firebasestorage.app',
  );

  /// iOS — register an iOS app in Firebase Console and replace appId with
  /// the value from Project Settings → Your apps → iOS app.
  /// Also download GoogleService-Info.plist and add to the iOS Runner target.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJFOj7F7I7-NIqclH4JLBhDZzvqb9_uIU',
    // TODO: Replace with real iOS appId from Firebase Console
    // Format: 1:<project_number>:ios:<sha256_hash>
    appId: '1:314717495726:ios:d71b1db1dd5c01dbc0a83f',
    messagingSenderId: '314717495726',
    projectId: 'honeychain-40065',
    authDomain: 'honeychain-40065.firebaseapp.com',
    storageBucket: 'honeychain-40065.firebasestorage.app',
    iosBundleId: 'com.honeychain.app',
  );
}

