// File generated by FlutterFire CLI & customized for HoneyChain
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJFOj7F7I7-NIqclH4JLBhDZzvqb9_uIU',
    appId: '1:314717495726:web:d71b1db1dd5c01dbc0a83f',
    messagingSenderId: '314717495726',
    projectId: 'honeychain-40065',
    authDomain: 'honeychain-40065.firebaseapp.com',
    storageBucket: 'honeychain-40065.firebasestorage.app',
    measurementId: 'G-SVJJXDM34B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFOj7F7I7-NIqclH4JLBhDZzvqb9_uIU',
    appId: '1:314717495726:web:d71b1db1dd5c01dbc0a83f',
    messagingSenderId: '314717495726',
    projectId: 'honeychain-40065',
    authDomain: 'honeychain-40065.firebaseapp.com',
    storageBucket: 'honeychain-40065.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJFOj7F7I7-NIqclH4JLBhDZzvqb9_uIU',
    appId: '1:314717495726:web:d71b1db1dd5c01dbc0a83f',
    messagingSenderId: '314717495726',
    projectId: 'honeychain-40065',
    authDomain: 'honeychain-40065.firebaseapp.com',
    storageBucket: 'honeychain-40065.firebasestorage.app',
    iosBundleId: 'com.honeychain.app',
  );
}
