import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Flag-free Language model representing one of the 22 supported languages
class AppLanguage {
  final String code;
  final String name;
  final String nativeName;

  const AppLanguage({
    required this.code,
    required this.name,
    required this.nativeName,
  });
}

/// Centralized localization service supporting 22 languages (Flag-free & Text-based)
class LanguageController extends ChangeNotifier {
  static const String _prefKey = 'honeychain_language_code';

  static const List<AppLanguage> supportedLanguages = [
    AppLanguage(code: 'en', name: 'English', nativeName: 'English'),
    AppLanguage(code: 'as', name: 'Assamese', nativeName: 'অসমীয়া'),
    AppLanguage(code: 'bn', name: 'Bengali', nativeName: 'বাংলা'),
    AppLanguage(code: 'brx', name: 'Bodo', nativeName: 'बड़ो'),
    AppLanguage(code: 'doi', name: 'Dogri', nativeName: 'डोगरी'),
    AppLanguage(code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી'),
    AppLanguage(code: 'hi', name: 'Hindi', nativeName: 'हिन्दी'),
    AppLanguage(code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ'),
    AppLanguage(code: 'ks', name: 'Kashmiri', nativeName: 'کٲشُر / कश्मीरी'),
    AppLanguage(code: 'kok', name: 'Konkani', nativeName: 'कोंकणी'),
    AppLanguage(code: 'mai', name: 'Maithili', nativeName: 'मैथिली'),
    AppLanguage(code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം'),
    AppLanguage(code: 'mni', name: 'Manipuri', nativeName: 'মণিপুরী'),
    AppLanguage(code: 'mr', name: 'Marathi', nativeName: 'मराठी'),
    AppLanguage(code: 'ne', name: 'Nepali', nativeName: 'नेपाली'),
    AppLanguage(code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ'),
    AppLanguage(code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ'),
    AppLanguage(code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्'),
    AppLanguage(code: 'sat', name: 'Santali', nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ'),
    AppLanguage(code: 'sd', name: 'Sindhi', nativeName: 'سنڌي'),
    AppLanguage(code: 'ta', name: 'Tamil', nativeName: 'தமிழ்'),
    AppLanguage(code: 'te', name: 'Telugu', nativeName: 'తెలుగు'),
    AppLanguage(code: 'ur', name: 'Urdu', nativeName: 'اردو'),
  ];

  String _currentLanguageCode = 'en';

  String get currentLanguageCode => _currentLanguageCode;

  AppLanguage get currentLanguage => supportedLanguages.firstWhere(
        (l) => l.code == _currentLanguageCode,
        orElse: () => supportedLanguages.first,
      );

  LanguageController() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguageCode = prefs.getString(_prefKey) ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String code) async {
    if (_currentLanguageCode == code) return;
    _currentLanguageCode = code;
    notifyListeners();
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefKey, code);
  }

  /// Translate a key into the currently selected language
  String tr(String key) {
    final map = _translations[_currentLanguageCode] ?? _translations['en']!;
    return map[key] ?? _translations['en']![key] ?? key;
  }

  // Core dictionary for UI strings
  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'HoneyChain',
      'home': 'Home',
      'hives': 'Hives',
      'profile': 'Profile',
      'add_hive': 'Add hive',
      'create_manage_hive': 'Create and manage your hives',
      'recent_hives': 'Hives',
      'your_active_fields': 'Your active apiaries',
      'show_more': 'Show all',
      'all_hives': 'All hives',
      'search_hives_hint': 'Search hives...',
      'search_language_hint': 'Search language...',
      'no_hives_yet': 'No hives added yet',
      'no_hives_subtitle': 'Create your first hive to start tracking harvest.',
      'add_first_hive': 'Add first hive',
      'field_overview': 'Hive overview',
      'overview': 'Overview',
      'production': 'Production',
      'inspection': 'Inspection',
      'notes': 'Notes',
      'edit_hive': 'Edit field',
      'delete_hive': 'Delete field',
      'save_hive': 'Save field',
      'cancel': 'Cancel',
      'delete_confirm_title': 'Delete this field?',
      'delete_confirm_msg': 'This action cannot be undone.',
      'delete': 'Delete',
      'account': 'Account',
      'edit_profile': 'Edit profile',
      'change_password': 'Change password',
      'appearance': 'Appearance',
      'theme': 'Appearance',
      'theme_settings': 'Appearance',
      'language': 'Language',
      'preferences': 'Preferences',
      'notifications': 'Notifications',
      'about': 'About HoneyChain',
      'security': 'Security',
      'logout': 'Log out',
      'light': 'Light',
      'dark': 'Dark',
      'system_default': 'System',
      'light_subtitle': 'Bright theme for daytime operational use.',
      'dark_subtitle': 'Low-light contrast theme for night monitoring.',
      'system_default_subtitle': 'Match device system appearance.',
      'select_language': 'Choose language',
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'harvest_overview_sub': "Here's your harvest overview.",
      'todays_progress': "Today's progress",
      'current_field': 'Current field',
      'machine': 'Machine',
      'machine_ready': 'Ready',
      'fuel_level': 'Fuel level',
      'weather': 'Weather',
      'maintenance_due': 'Maintenance due',
      'maintenance_sub': 'Service recommended soon.',
      'start_harvest': 'Start harvest',
      'pause': 'Pause',
      'resume_harvest': 'Resume harvest',
      'finish_harvest': 'Finish harvest',
      'harvesting_in_progress': 'Harvesting in progress',
      'time': 'Time',
      'harvested_area': 'Harvested area',
      'area_remaining': 'Area remaining',
      'harvest_history': 'Harvest history',
      'location': 'Location',
      'total_area': 'Total area',
      'harvested': 'Harvested',
      'progress': 'Progress',
      'in_progress': 'In Progress',
      'completed': 'completed',
      'sign_in_account': 'Sign In',
      'welcome_back': 'Welcome back',
      'sign_in_sub': 'Sign in to manage your fields and harvest operations.',
      'email_or_phone': 'Email or Phone',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'login': 'Sign In',
      'or': 'OR',
      'google_sign_in': 'Sign in with Google',
      'apple_sign_in': 'Sign in with Apple',
      'phone_sign_in': 'Sign in with Phone',
      'dont_have_account': 'New to HoneyChain?',
      'create_account': 'Create account',
      'create_business_account': 'Create Account',
      'get_started_sub': 'Enter your business details to start tracking operations.',
      'legal_business_name': 'Business Name',
      'already_have_account': 'Already have an account? Sign In',
      'phone_auth': 'Phone Verification',
      'verification_code': 'Verification Code',
      'verify_otp': 'Verify & Sign In',
      'back_to_sign_in': 'Back to Sign In',
      'resend_in': 'Resend code in',
      'resend_otp': 'Resend OTP',
      'reset_password': 'Reset Password',
      'reset_password_sub': 'Enter your email or phone to receive reset instructions.',
      'send_reset_link': 'Send Reset Link',
      'enter_mobile_otp': 'Enter phone number to receive verification code.',
      'send_otp': 'Send Code',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'update_password': 'Update Password',
      'password_updated': 'Password updated successfully',
      'view_hive_details': 'View Field Details',
      'role_operator': 'Senior Operations Manager',
      'active_hive': 'Active Hive / Field',
      'select_your_role': 'Select your role',
      'harvester': 'Harvester',
      'harvester_desc': 'Manage hives, submit collection requests',
      'collection_processing': 'Collection & Processing',
      'collection_desc': 'Accept & process collection requests',
      'lab_testing': 'Lab Testing',
      'lab_desc': 'Test samples, submit lab reports',
      'packaging': 'Packaging',
      'packaging_desc': 'Approve packaging, generate QR codes',
      'choose_role_subtitle': 'Choose your role in the HoneyChain supply chain',
      'create_request': 'Create Request',
      'active_requests': 'Active Requests',
      'total_hives': 'Total Hives',
      'completed': 'Completed',
      'estimated_quantity': 'Estimated Quantity (kg)',
      'submit_request': 'Submit Request',
      'recent_requests': 'Recent Requests',
      'no_requests_yet': 'No requests yet',
      'back_to_roles': 'Back to role selection',
      'harvester_login': 'Harvester Login',
      'collection_login': 'Collection & Processing Login',
      'lab_login': 'Lab Testing Login',
      'packaging_login': 'Packaging Login',
    },
    'hi': {
      'app_name': 'HoneyChain',
      'home': 'होम',
      'hives': 'खेत/छत्ता',
      'profile': 'प्रोफ़ाइल',
      'add_hive': 'खेत जोड़ें',
      'create_manage_hive': 'अपने खेत का प्रबंधन करें',
      'recent_hives': 'खेत और छत्ते',
      'show_more': 'सभी देखें',
      'all_hives': 'सभी खेत और छत्ते',
      'search_hives_hint': 'खेत खोजें...',
      'search_language_hint': 'भाषा खोजें...',
      'no_hives_yet': 'कोई खेत नहीं जोड़ा गया',
      'no_hives_subtitle': 'कटाई ट्रैक करने के लिए पहला खेत जोड़ें।',
      'add_first_hive': 'पहला खेत जोड़ें',
      'quick_insights': 'त्वरित जानकारी',
      'overview': 'अवलोकन',
      'production': 'उत्पादन',
      'inspection': 'निरीक्षण',
      'queen': 'रानी मक्खी',
      'notes': 'नोट्स',
      'edit_hive': 'संपादित करें',
      'delete_hive': 'हटाएं',
      'save_hive': 'सहेजें',
      'cancel': 'रद्द करें',
      'delete_confirm_title': 'क्या आप हटाना चाहते हैं?',
      'delete_confirm_msg': 'यह कार्रवाई वापस नहीं ली जा सकती।',
      'delete': 'हटाएं',
      'account': 'खाता',
      'edit_profile': 'प्रोफ़ाइल संपादित करें',
      'change_password': 'पासवर्ड बदलें',
      'appearance': 'दिखावट',
      'theme': 'थीम',
      'language': 'भाषा',
      'preferences': 'वरीयताएं',
      'notifications': 'सूचनाएं',
      'about': 'HoneyChain के बारे में',
      'security': 'सुरक्षा',
      'logout': 'लॉग आउट',
      'light': 'लाइट',
      'dark': 'डार्क',
      'system_default': 'सिस्टम डिफ़ॉल्ट',
      'select_language': 'भाषा चुनें',
      'current_password': 'वर्तमान पासवर्ड',
      'new_password': 'नया पासवर्ड',
      'confirm_password': 'पासवर्ड की पुष्टि करें',
      'update_password': 'पासवर्ड अपडेट करें',
      'name': 'नाम',
      'email': 'ईमेल',
      'phone': 'फ़ोन नंबर',
      'save_changes': 'बदलाव सहेजें',
      'today_overview': 'आज का अवलोकन',
      'harvested_area': 'काटा गया क्षेत्र',
      'working_hours': 'काम के घंटे',
      'current_field': 'वर्तमान खेत / छत्ता',
      'machine_status': 'मशीन स्थिति',
      'machine_ready': 'तैयार है',
      'fuel_level': 'ईंधन 72%',
      'weather': 'मौसम',
      'quick_alert': 'परिचालन चेतावनी',
      'start_harvesting': 'कटाई शुरू करें',
      'pause_harvesting': 'रोकें',
      'resume_harvesting': 'पुनः आरंभ करें',
      'finish_harvesting': 'कटाई समाप्त करें',
      'active_harvest': 'सक्रिय कटाई',
      'time_elapsed': 'काम का समय',
      'remaining_area': 'शेष क्षेत्र',
      'in_progress': 'प्रगति पर',
      'maintenance_alert': '12 परिचालन घंटों में रखरखाव देय',
      'greeting_harvester': 'नमस्ते, ऑपरेटर',
      'location': 'स्थान',
      'crop': 'फ़सल',
      'progress': 'कटाई प्रगति',
      'harvest_history': 'कटाई का इतिहास',
      'select_your_role': 'अपनी भूमिका चुनें',
      'harvester': 'मधुमक्खी पालक',
      'harvester_desc': 'छत्ते प्रबंधित करें, संग्रह अनुरोध भेजें',
      'collection_processing': 'संग्रह और प्रसंस्करण',
      'collection_desc': 'संग्रह अनुरोध स्वीकार करें',
      'lab_testing': 'प्रयोगशाला परीक्षण',
      'lab_desc': 'नमूने परीक्षण करें, रिपोर्ट भेजें',
      'packaging': 'पैकेजिंग',
      'packaging_desc': 'पैकेजिंग स्वीकृत करें, QR कोड बनाएं',
      'choose_role_subtitle': 'HoneyChain आपूर्ति श्रृंखला में अपनी भूमिका चुनें',
      'create_request': 'अनुरोध बनाएं',
      'active_requests': 'सक्रिय अनुरोध',
      'total_hives': 'कुल छत्ते',
      'completed': 'पूर्ण',
      'estimated_quantity': 'अनुमानित मात्रा (किग्रा)',
      'submit_request': 'अनुरोध भेजें',
      'recent_requests': 'हाल के अनुरोध',
      'no_requests_yet': 'अभी तक कोई अनुरोध नहीं',
      'back_to_roles': 'भूमिका चयन पर वापस जाएं',
      'harvester_login': 'मधुमक्खी पालक लॉगिन',
      'collection_login': 'संग्रह लॉगिन',
      'lab_login': 'प्रयोगशाला लॉगिन',
      'packaging_login': 'पैकेजिंग लॉगिन',
    },
    'bn': {
      'app_name': 'HoneyChain',
      'home': 'হোম',
      'hives': 'ক্ষেত/হাইভ',
      'profile': 'প্রোফাইল',
      'add_hive': 'ক্ষেত্র যোগ করুন',
      'recent_hives': 'সাম্প্রতিক ক্ষেত্র',
      'show_more': 'আরও দেখুন',
      'all_hives': 'সমস্ত ক্ষেত্র',
      'search_hives_hint': 'ক্ষেত্র খুঁজুন...',
      'search_language_hint': 'ভাষা খুঁজুন...',
      'no_hives_yet': 'কোন ক্ষেত্র যোগ করা হয়নি',
      'no_hives_subtitle': 'ট্র্যাকিং শুরু করতে প্রথম ক্ষেত্র যোগ করুন।',
      'add_first_hive': 'প্রথম ক্ষেত্র যোগ করুন',
      'quick_insights': 'দ্রুত তথ্য',
      'overview': 'সংক্ষিপ্ত বিবরণ',
      'cancel': 'বাতিল',
      'delete': 'মুছুন',
      'account': 'অ্যাকাউন্ট',
      'theme': 'থিম',
      'language': 'ভাষা',
      'notifications': 'বিজ্ঞপ্তি',
      'logout': 'লগ আউট',
      'light': 'লাইট',
      'dark': 'ডার্ক',
      'system_default': 'সিস্টেম ডিফোল্ট',
      'select_language': 'ভাষা নির্বাচন করুন',
      'today_overview': 'আজকের ওভারভিউ',
      'harvested_area': 'কাটা এলাকা',
      'working_hours': 'কাজের সময়',
      'current_field': 'বর্তমান ক্ষেত্র',
      'machine_status': 'মেশিনের অবস্থা',
      'start_harvesting': 'কাটা শুরু করুন',
      'pause_harvesting': 'থামুন',
      'resume_harvesting': 'পুনরায় শুরু করুন',
      'finish_harvesting': 'সম্পন্ন করুন',
    },
    'te': {
      'app_name': 'HoneyChain',
      'home': 'హోమ్',
      'hives': 'పొలం/హైవ్',
      'profile': 'ప్రొఫైల్',
      'add_hive': 'పొలం జోడించండి',
      'recent_hives': 'ఇటీవలి పొలాలు',
      'show_more': 'మరిన్ని చూడండి',
      'all_hives': 'అన్ని పొలాలు',
      'search_hives_hint': 'శోధించండి...',
      'search_language_hint': 'భాష శోధించండి...',
      'no_hives_yet': 'ఇంకా పొలాలు జోడించబడలేదు',
      'no_hives_subtitle': 'కోతను ట్రాక్ చేయడానికి మొదటి పొలాన్ని జోడించండి.',
      'add_first_hive': 'మొదటి పొలం జోడించండి',
      'quick_insights': 'శీఘ్ర వివరణ',
      'overview': 'అవలోకనం',
      'cancel': 'రద్దు చేయి',
      'delete': 'తొలగించు',
      'account': 'ఖాతా',
      'theme': 'థీమ్',
      'language': 'భాష',
      'notifications': 'నోటిఫికేషన్లు',
      'logout': 'లాగ్ అవుట్',
      'light': 'లైట్',
      'dark': 'డార్క్',
      'system_default': 'సిస్టమ్ డిఫాల్ట్',
      'select_language': 'భాషను ఎంచుకోండి',
      'today_overview': 'ఈరోజు అవలోకనం',
      'harvested_area': 'కోసిన విస్తీర్ణం',
      'working_hours': 'పని వేళలు',
      'current_field': 'ప్రస్తుత పొలం',
      'machine_status': 'మిషన్ పరిస్థితి',
      'start_harvesting': 'కోత ప్రారంభించండి',
      'pause_harvesting': 'పాజ్ చేయి',
      'resume_harvesting': 'తిరిగి ప్రారంభించు',
      'finish_harvesting': 'పూర్తి చేయి',
    },
    'mr': {
      'app_name': 'HoneyChain',
      'home': 'होम',
      'hives': 'शेती/पोळे',
      'profile': 'प्रोफाइल',
      'add_hive': 'शेती जोडा',
      'recent_hives': 'नुकतीच शेती',
      'show_more': 'अधिक पहा',
      'all_hives': 'सर्व शेती',
      'search_hives_hint': 'शोधा...',
      'search_language_hint': 'भाषा शोधा...',
      'no_hives_yet': 'अजून कोणतीही शेती जोडलेली नाही',
      'no_hives_subtitle': 'कापणीचा मागोवा घेण्यासाठी पहिली शेती जोडा.',
      'add_first_hive': 'पहिली शेती जोडा',
      'quick_insights': 'जलद माहिती',
      'overview': 'आढावा',
      'cancel': 'रद्द करा',
      'delete': 'काढून टाका',
      'account': 'खाते',
      'theme': 'थीम',
      'language': 'भाषा',
      'notifications': 'सूचना',
      'logout': 'लॉग आउट',
      'light': 'लाइट',
      'dark': 'डार्क',
      'system_default': 'सिस्टम डीफॉल्ट',
      'select_language': 'भाषा निवडा',
      'today_overview': 'आजचा आढावा',
      'harvested_area': 'कापणी केलेले क्षेत्र',
      'working_hours': 'कामाचे तास',
      'current_field': 'सध्याचे क्षेत्र',
      'machine_status': 'मशीनची स्थिती',
      'start_harvesting': 'कापणी सुरू करा',
      'pause_harvesting': 'थांबवा',
      'resume_harvesting': 'पुन्हा सुरू करा',
      'finish_harvesting': 'पूर्ण करा',
    },
    'ta': {
      'app_name': 'HoneyChain',
      'home': 'முகப்பு',
      'hives': 'நிலம்/தேனீக்கூடு',
      'profile': 'சுயவிவரம்',
      'add_hive': 'நிலம் சேர்',
      'recent_hives': 'சமீபத்திய நிலங்கள்',
      'show_more': 'மேலும் காண்க',
      'all_hives': 'அனைத்து நிலங்களும்',
      'search_hives_hint': 'தேடுக...',
      'search_language_hint': 'மொழி தேடுக...',
      'no_hives_yet': 'இன்னும் நிலங்கள் சேர்க்கப்படவில்லை',
      'no_hives_subtitle': 'அறுவடையைக் கண்காணிக்க முதல் நிலத்தைச் சேர்க்கவும்.',
      'add_first_hive': 'முதல் நிலம் சேர்',
      'quick_insights': 'விரைவுத் தகவல்',
      'overview': 'மேலோட்டம்',
      'cancel': 'ரத்துசெய்',
      'delete': 'நீக்கு',
      'account': 'கணக்கு',
      'theme': 'தீம்',
      'language': 'மொழி',
      'notifications': 'அறிவிப்புகள்',
      'logout': 'வெளியேறு',
      'light': 'லைட்',
      'dark': 'டார்க்',
      'system_default': 'சிஸ்டம் இயல்புநிலை',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'today_overview': 'இன்றைய கண்ணோட்டம்',
      'harvested_area': 'அறுவடை செய்யப்பட்ட பகுதி',
      'working_hours': 'வேலை நேரம்',
      'current_field': 'தற்போதைய நிலம்',
      'machine_status': 'இயந்திரத்தின் நிலை',
      'start_harvesting': 'அறுவடையைத் தொடங்கு',
      'pause_harvesting': 'நிறுத்து',
      'resume_harvesting': 'மீண்டும் தொடங்கு',
      'finish_harvesting': 'முடி',
    },
    'gu': {
      'app_name': 'HoneyChain',
      'home': 'હોમ',
      'hives': 'ખેતર/પૂડો',
      'profile': 'પ્રોફાઇલ',
      'add_hive': 'ખેતર ઉમેરો',
      'recent_hives': 'તાજેતરના ખેતરો',
      'show_more': 'વધુ જુઓ',
      'all_hives': 'તમામ ખેતરો',
      'search_hives_hint': 'શોધો...',
      'search_language_hint': 'ભાષા શોધો...',
      'no_hives_yet': 'હજી સુધી કોઈ ખેતર ઉમેરાયું નથી',
      'no_hives_subtitle': 'કાપણી ટ્રેક કરવા માટે પ્રથમ ખેતર ઉમેરો.',
      'add_first_hive': 'પ્રથમ ખેતર ઉમેરો',
      'quick_insights': 'ઝડપી ઝાંખી',
      'overview': 'ઝાંખી',
      'cancel': 'રદ કરો',
      'delete': 'કાઢી નાખો',
      'account': 'ખાતું',
      'theme': 'થીમ',
      'language': 'ભાષા',
      'notifications': 'સૂચનાઓ',
      'logout': 'લૉગ આઉટ',
      'light': 'લાઇટ',
      'dark': 'ડાર્ક',
      'system_default': 'સિસ્ટમ ડિફૉલ્ટ',
      'select_language': 'ભાષા પસંદ કરો',
      'today_overview': 'આજનો ઓવરવ્યૂ',
      'harvested_area': 'કાપણી કરેલ વિસ્તાર',
      'working_hours': 'કામના કલાકો',
      'current_field': 'હાલનું ખેતર',
      'machine_status': 'મશીનની સ્થિતિ',
      'start_harvesting': 'કાપણી શરૂ કરો',
      'pause_harvesting': 'અટકાવો',
      'resume_harvesting': 'ફરી શરૂ કરો',
      'finish_harvesting': 'પૂર્ણ કરો',
    },
    'kn': {
      'app_name': 'HoneyChain',
      'home': 'ಮುಖಪುಟ',
      'hives': 'ಹೊಲ/ಸಾಕಣೆ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'add_hive': 'ಹೊಲ ಸೇರಿಸಿ',
      'recent_hives': 'ಇತ್ತೀಚಿನ ಹೊಲಗಳು',
      'show_more': 'ಇನ್ನಷ್ಟು ನೋಡಿ',
      'all_hives': 'ಎಲ್ಲಾ ಹೊಲಗಳು',
      'search_hives_hint': 'ಹುಡುಕಿ...',
      'search_language_hint': 'ಭಾಷೆ ಹುಡುಕಿ...',
      'no_hives_yet': 'ಇನ್ನೂ ಯಾವುದೇ ಹೊಲ ಸೇರಿಸಲಾಗಿಲ್ಲ',
      'no_hives_subtitle': 'ಕೊಯ್ಲು ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ನಿಮ್ಮ ಮೊದಲ ಹೊಲವನ್ನು ಸೇರಿಸಿ.',
      'add_first_hive': 'ಮೊದಲ ಹೊಲ ಸೇರಿಸಿ',
      'quick_insights': 'ತ್ವರಿತ ಮಾಹಿತಿಗಳು',
      'overview': 'ಅವಲೋಕನ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'delete': 'ಅಳಿಸಿ',
      'account': 'ಖಾತೆ',
      'theme': 'ಥೀಮ್',
      'language': 'ಭಾಷೆ',
      'notifications': 'ಸೂಚನೆಗಳು',
      'logout': 'ಲॉग್‌ಔಟ್',
      'light': 'ಲೈಟ್',
      'dark': 'ಡಾರ್ಕ್',
      'system_default': 'ಸಿಸ್ಟಮ್ ಡೀಫಾಲ್ಟ್',
      'select_language': 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'today_overview': 'ಇಂದಿನ ವಿವರ',
      'harvested_area': 'ಕೊಯ್ಲು ಮಾಡಿದ ಪ್ರದೇಶ',
      'working_hours': 'ಕೆಲಸದ ಸಮಯ',
      'current_field': 'ಪ್ರಸ್ತುತ ಹೊಲ',
      'machine_status': 'ಯಂತ್ರದ ಸ್ಥಿತಿ',
      'start_harvesting': 'ಕೊಯ್ಲು ಪ್ರಾರಂಭಿಸಿ',
      'pause_harvesting': 'ವಿರಾಮಗೊಳಿಸಿ',
      'resume_harvesting': 'ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ',
      'finish_harvesting': 'ಪೂರ್ಣಗೊಳಿಸಿ',
    },
  };
}

/// Extension on BuildContext for quick reactive translation lookups
extension LocalizationContextX on BuildContext {
  String tr(String key) {
    return watch<LanguageController>().tr(key);
  }
}
